name: sentiment
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.9
  - numpy
  - pandas
  - scikit-learn
  - nltk
  - spacy
  - tensorflow
  - pytorch
  - matplotlib
  - jupyter
  - seaborn
  - gensim
  - transformers
  - regex
  - tqdm
  - wordcloud
  - tensorflow 
  - tensorflow-hub
  - shap

# Optional pip packages
  - pip:
      - sentence-transformers
